name: GitHub Actions AnxietyAlly
run-name: ${{ github.actor }} is pushing commit(s)
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building has begun"
      - uses: actions/checkout@v4
      - run: npm ci
        working-directory: frontend
      - run: npm ci
        working-directory: backend/accounts/code
      - run: npm ci
        working-directory: backend/apigateway/code
      - run: npm run build --if-present
        working-directory: frontend
      - run: npm run build --if-present
        working-directory: backend/accounts/code
      - run: npm run build --if-present
        working-directory: backend/apigateway/code
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - run: echo "Testing has begun"
    - uses: actions/checkout@v4
    - run: npm run test
      working-directory: frontend
    - run: npm run test-coverage
      working-directory: frontend
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
